version: "3"
services:
  api:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - MONGO_URL=${DB_HOST}
      - API_PORT=${API_PORT}
      - DB_PORT=${DB_PORT}
  db:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
networks:
  default:
    external:
      name: gameapi